version: '3.8'

services:
  api:
    build:
      context: ./RabbitQuestAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Server=db;Database=QuestDatabase;User Id=sa;Password=Nz_E24a6rYnC;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - questnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nz_E24a6rYnC
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - questnet

networks:
  questnet:
    driver: bridge

volumes:
  sqldata: